on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '40 * * * *'

jobs:
  tweetshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generating tweetshot
        id: tweet
        uses: mborejdo/action-wss@refs/heads/master
        with:
          mode: 'tweet'
          cli: ''
          infile: 'twitter.html?id=20'
          outfile: 'tweetx'
      - name: Uploading all tweetshots
        uses: actions/upload-artifact@v2
        with:
          name: tweet
          path: '/home/runner/work/_temp/_github_home/*.png'