on: [push]

jobs:
  tweetshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generating tweetshot
        id: tweet
        uses: mborejdo/actions@refs/heads/master
        with:
          mode: 'tweet'
          cli: ''
          infile: '1463560516882866179'
          outfile: 'tweet'
      - name: Uploading all tweetshots
        uses: actions/upload-artifact@v2
        with:
          name: tweet
          path: '/home/runner/work/_temp/_github_home/*.png'