on:
  push:
    branches: [ main ]

jobs:
  tweetshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generating tweetshot
        id: tweet
        uses: mborejdo/action-wss@refs/heads/master
        with:
          mode: 'tweet'
          cli: ''
          infile: 'twitter.html?data=%7B%22id%22%3A%2220%22%2C%20%22mode%22%3A%20%22xlatest%22%7D'
          outfile: 'tweetx'
      - name: Uploading all tweetshots
        uses: actions/upload-artifact@v2
        with:
          name: tweet
          path: '/home/runner/work/_temp/_github_home/*.png'